"""
ServiceNow client — create, update, and close incidents with RCA notes.

Replace demo credentials in .env:
  SNOW_INSTANCE=dev12345.service-now.com
  SNOW_USER=admin
  SNOW_PASS=Admin@1234
  SNOW_ASSIGNMENT_GROUP=SAP-BASIS-TEAM
"""
import os, httpx, logging
from datetime import datetime

logger = logging.getLogger(__name__)

SNOW_INSTANCE       = os.getenv("SNOW_INSTANCE", "dev12345.service-now.com")
SNOW_USER           = os.getenv("SNOW_USER", "admin")
SNOW_PASS           = os.getenv("SNOW_PASS", "Admin@1234")
SNOW_ASSIGNMENT_GRP = os.getenv("SNOW_ASSIGNMENT_GROUP", "SAP-BASIS-TEAM")

_BASE = f"https://{SNOW_INSTANCE}/api/now/table"
_AUTH = (SNOW_USER, SNOW_PASS)
_HDR  = {"Content-Type": "application/json", "Accept": "application/json"}

# SAP priority → ServiceNow impact/urgency mapping
_PRIORITY_MAP = {
    "critical": {"impact": "1", "urgency": "1"},
    "high":     {"impact": "2", "urgency": "1"},
    "medium":   {"impact": "2", "urgency": "2"},
    "low":      {"impact": "3", "urgency": "3"},
}


def create_snow_incident(alm_incident: dict) -> str:
    """
    Create a ServiceNow incident from a SAP Cloud ALM alert.
    Returns the ServiceNow sys_id (or mock ID in demo mode).
    """
    if _is_demo():
        sys_id = f"SNOW-DEMO-{alm_incident['id']}"
        logger.info("[SNOW-DEMO] Created incident %s for %s", sys_id, alm_incident["id"])
        return sys_id

    prio = _PRIORITY_MAP.get(alm_incident.get("priority", "medium"), _PRIORITY_MAP["medium"])
    payload = {
        "short_description": f"[SAP] {alm_incident.get('title', '')}",
        "description": (
            f"SAP Cloud ALM Alert\n"
            f"Incident ID : {alm_incident['id']}\n"
            f"Error Code  : {alm_incident.get('error_code', 'N/A')}\n"
            f"System      : {alm_incident.get('system_id', 'SAP-PRD')}\n"
            f"Priority    : {alm_incident.get('priority', 'medium').upper()}\n"
            f"Detected at : {alm_incident.get('created_at', datetime.utcnow().isoformat())}"
        ),
        "assignment_group": SNOW_ASSIGNMENT_GRP,
        "category": "SAP",
        "subcategory": alm_incident.get("error_code", "OTHER"),
        **prio,
    }
    r = httpx.post(f"{_BASE}/incident", auth=_AUTH, headers=_HDR, json=payload)
    r.raise_for_status()
    sys_id = r.json()["result"]["sys_id"]
    logger.info("Created ServiceNow incident %s for ALM %s", sys_id, alm_incident["id"])
    return sys_id


def update_snow_with_rca(sys_id: str, rca: str, steps: list[str], confidence: float):
    """Post RCA analysis and remediation steps as a work note."""
    steps_text = "\n".join(steps)
    note = (
        f"[AI RCA — confidence {confidence:.0%}]\n\n"
        f"Root Cause:\n{rca}\n\n"
        f"Remediation Steps:\n{steps_text}\n\n"
        f"Generated by SAP Self-Healing Agent at {datetime.utcnow().isoformat()}Z"
    )
    if _is_demo():
        logger.info("[SNOW-DEMO] RCA posted to %s: %s", sys_id, note[:80])
        return

    r = httpx.patch(
        f"{_BASE}/incident/{sys_id}",
        auth=_AUTH, headers=_HDR,
        json={"work_notes": note},
    )
    r.raise_for_status()
    logger.info("RCA posted to ServiceNow %s", sys_id)


def close_snow_incident(sys_id: str, resolution_note: str, confidence: float):
    """
    Close the ServiceNow incident.
    - confidence >= 0.85 → auto-resolved (close_code = Solved by AI)
    - confidence <  0.85 → assign to team for manual review
    """
    if _is_demo():
        action = "RESOLVED" if confidence >= 0.85 else "ASSIGNED-FOR-REVIEW"
        logger.info("[SNOW-DEMO] %s incident %s: %s", action, sys_id, resolution_note[:80])
        return

    if confidence >= 0.85:
        payload = {
            "state": "6",                          # Resolved
            "close_code": "Solved (Permanently)",
            "close_notes": resolution_note,
            "resolved_at": datetime.utcnow().isoformat(),
        }
    else:
        payload = {
            "state": "2",                          # In Progress
            "assignment_group": SNOW_ASSIGNMENT_GRP,
            "work_notes": f"AI confidence {confidence:.0%} — manual review required.\n{resolution_note}",
        }

    r = httpx.patch(f"{_BASE}/incident/{sys_id}", auth=_AUTH, headers=_HDR, json=payload)
    r.raise_for_status()
    logger.info("ServiceNow %s updated (confidence=%.2f)", sys_id, confidence)


def _is_demo() -> bool:
    return "demo" in SNOW_INSTANCE.lower() or not SNOW_USER or SNOW_USER == "admin"
